apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-app
  template:
    metadata:
      labels:
        app: f1-app
    spec:
      containers:
      - name: f1-app
        image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/f1-repo/f1-analysis-app:latest
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: f1-app-service
spec:
  type: LoadBalancer
  selector:
    app: f1-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
